### ISSUE TITLE
May plugin activation be required?

### ISSUE THREAD

**Issue by carstingaxion** [swissspidy/wp-plugin-check-action#61] opened 2024-04-01 01:28 UTC
Hello @swissspidy !

I suggested using this cool action for [GatherPress](https://github.com/GatherPress/gatherpress), but we ran into [a subtle problem during the first run](https://github.com/GatherPress/gatherpress/actions/runs/8342340877/job/22830264159?pr=616), unfortunately.

While @mauteri suggested to call `wp plugin activate gatherpress` from within our workflow, I think it might be needed to this on the wp-plugin-check-action itself?

Probably somewhere around here, between 108 and 109:

https://github.com/swissspidy/wp-plugin-check-action/blob/8ee6b81574b78daa89c1487b5e3e2337b03dbf29/action.yml#L108-L109

May I be wrong? What is the expectated behaviour with plugins that make use of the activation hook AND create custom tables? Are such plugins - in theory - testable with the action?

**Comment by swissspidy** [comment] 2024-04-03 13:05
Heya, thanks for opening this!

No, plugin activation is not required.

Plugin Check performs two kinds of checks:

* Static analysis — the code is tested by _reading_ it instead of _running_ it. These are mostly PHPCS tests.
* Runtime analysis — the plugin is activated as part of this check, _but on a separate WordPress install with a different database table prefix_. This is automatically handled by Plugin Check.

So to answer your question:

> What is the expectated behaviour with plugins that make use of the activation hook AND create custom tables? Are such plugins - in theory - testable with the action?

Yes, these plugins are testable. You should not need to do anything special to make it work.

I think what you might be running into is https://github.com/WordPress/plugin-check/issues/234

If you manually install the Plugin Check plugin on a development site and run it against GatherPress, are you getting the same database errors?

I'll try to reproduce this as well on my end with just the plugin.

**Comment by swissspidy** [comment] 2024-04-03 13:17
Hmm when I'm running `wp plugin check gatherpress --format=json --require=./wp-content/plugins/plugin-check/cli.php` locally it works just fine.

In any case, the GitHub action is still working fine for you and there's no error, so not really urgent to look into it imho :)

**Comment by pedro-mendonca** [comment] 2024-04-03 18:59
Hi, with the new WP 6.5 and dependencies I'm getting an error of a plugin that depends of another.
```
Warning: Failed to activate plugin. [Plugin Name] requires 1 plugin to be installed and activated: [plugin-dependency]. .
Error: No plugins activated.
Error: Process completed with exit code 1.
```
And with this, the test fails.
The current alternative is setting wp_version to 6.4, which doesn't rely on the dependencies and the plugin is correctly activated.

Maybe the action could check the plugin dependencies and activate them also.

**Comment by swissspidy** [comment] 2024-04-03 19:29
@pedro-mendonca Mind creating a new issue for that? It's really separate and I am basically about to close this one.

It's a great question though! Do you have a sample repo you could point me to?

I might add a `plugin-dependencies` input or so that allows you to specify the dependencies.

WP-CLI is a good point as well and [WP-CLI will soon gain these capabilities](https://github.com/wp-cli/extension-command/issues/407). But in the meantime we'll have to sort this out ourselves. Even if that means writing some hacky code to find the dependencies.

**Comment by pedro-mendonca** [comment] 2024-04-03 19:30
Sure, I'll create another issue, I'm sorry I thought it might be related :)

**Comment by swissspidy** [comment] 2024-04-04 09:41
I have to circle back on this one:

Plugin activation is **not required** for static checks, _but_ it is required for runtime checks.

So turns out I was not doing the latter here, which means the runtime checks were simply not running. But that's not a big deal, the rest is still working even without plugin activation.

**Comment by swissspidy** [comment] 2024-04-08 11:34
Fixed in #67

**Closed by swissspidy** 2024-04-08 11:34 UTC
Labels: enhancement, question

**Comment by carstingaxion** [comment] 2024-04-08 11:48
Hallo @swissspidy 

I'm sorry you had to deal with all this on your own. I for sure wanted to come back to you earlier.

I haven't even looked into your changes yet. But great, you did. Will jump right into it now!

Thanks.

**Comment by carstingaxion** [comment] 2024-04-08 11:54
Cool. Happy to see your changes touched the lines 108ff. and I was not that wrong.

Thank you very much for your detailed explanation and the fast solution @swissspidy!
